image: ruby:3.1  # Ruby imajı
image: rvancea/maven-chrome-jdk8:latest

before_script:
  # Maven və Java-nı quraşdırırıq
  - apt-get update && apt-get install -y maven openjdk-11-jdk

stages:
  - build
  - test
  - deploy

# Build mərhələsi: Java kodunu təmizləyib qurur
build:
  stage: build
  script:
    - mvn clean install  # Maven ilə layihəni qurmaq
    - mvn compile

# Test mərhələsi: Testləri işə salır
test:
  stage: test
  script:
    - mvn clean test  # Testləri işə salmaq

# Deploy mərhələsi: Tətbiqi serverə yerləşdirir
deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp target/myapp.jar user@server:/path/to/deploy  # SSH ilə faylı serverə göndərmək
  only:
    - master  # Yalnız master branch-da deploy etmək
