image: maven:3.8.6-eclipse-temurin-17

stages:
  - build
  - sast_scan

build:
  stage: build
  script:
    - echo "Building Java project..."
    - mvn clean package -DskipTests -X
  artifacts:
    paths:
      - target/*.jar

sast_scan:
  stage: sast_scan
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:latest
  script:
    - echo "Running SAST Scan..."
    - /analyzer run | tee sast_results.json
  artifacts:
    reports:
      sast: sast_results.json
    paths:
      - sast_results.json 
