stages:
  - build
  - test
  - deploy

# Java 17 və Maven imajını istifadə edirik
image: maven:3.8.4-openjdk-17

before_script:
  - apt-get update && apt-get install -y maven openjdk-17-jdk  # Java 17 və Maven quraşdırırıq
  - java -version  # Java versiyasını yoxlayırıq
  - mvn -version   # Maven versiyasını yoxlayırıq

# Build mərhələsi: Java kodunu təmizləyib qurur
build:
  stage: build
  script:
    - mvn clean install -Dmaven.compiler.source=17 -Dmaven.compiler.target=17  # Java 17 istifadə edirik
    - mvn compile  # Layihəni təmizləyib, yenidən qurmaq
  artifacts:
    paths:
      - target/*.jar  # JAR faylını artefakt olaraq saxlayırıq
  only:
    - sprint1/sarkhan  # Yalnız sprint1/sarkhan branch-da işləyir

# Test mərhələsi: Testləri işə salır
test:
  stage: test
  script:
    - mvn test  # Testləri işə salmaq
  only:
    - sprint1/sarkhan  # Yalnız sprint1/sarkhan branch-da işləyir

# Deploy mərhələsi: Tətbiqi serverə yerləşdirir
deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp target/myapp.jar user@server:/path/to/deploy  # Faylı serverə göndəririk
  only:
    - sprint1/sarkhan  # Yalnız sprint1/sarkhan branch-da deploy edir
