services:
  users_service:
    container_name: user
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: User
    ports:
      - '5450:5432'
    volumes:
      - UserData:/var/lib/postgresql/data
    networks:
      - bendis
  product_service:
    container_name: product
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Product
    ports:
      - '5451:5432'
    volumes:
      - ProductData:/var/lib/postgresql/data
    networks:
      - bendis
  story_service:
    container_name: story
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Story
    ports:
      - '5452:5432'
    volumes:
      - StoryData:/var/lib/postgresql/data
    networks:
      - bendis
  redis:
    image: redis:7.2
    ports:
      - '6380:6379'

volumes:
  UserData: {}
  ProductData: {}
  StoryData: {}
  redis_data: {}

networks:
  bendis:
    driver: bridge
