services:
  users_service:
    container_name: user
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: User
    ports:
      - '5450:5432'
    volumes:
      - UserData:/var/lib/postgresql/data
    networks:
      - bendis
  product_service:
    container_name: product
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Product
    ports:
      - '5451:5432'
    volumes:
      - ProductData:/var/lib/postgresql/data
    networks:
      - bendis
volumes:
  UserData: {}
  ProductData: {}

networks:
  bendis:
    driver: bridge
